version: '3'
services:
  web:
    image: marketplace
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/app:z
      - ./storage/app/public:/app/public/storage
    environment:
      PHP_DEBUGGER: xdebug
      PHP_DISPLAY_ERRORS: 1
      XDEBUG_REMOTE_AUTOSTART: 0
      XDEBUG_REMOTE_HOST: 172.19.0.1
      WEB_DOCUMENT_ROOT: "/app/public"
  db:
    #image: mysql:5.7
    #image: mariadb:10.2
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - databasevol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: bitnami/redis:4.0
    ports:
      - "6378:6379"
    volumes:
      - cachevol:/bitnami
    environment:
      REDIS_PASSWORD: root
  selenium:
    image: selenium/standalone-chrome-debug:3.8.1
    #image: selenium/standalone-firefox-debug:3.8.1
    depends_on:
      - web
    ports:
      - "4444:4444"
      - "5900:5900"
    network_mode: "host"
volumes:
  databasevol:
  cachevol: