version: '3'
services:
  selenium:
    image: selenium/standalone-chrome-debug:3.8.1
    #image: selenium/standalone-firefox-debug:3.8.1
    depends_on:
      - web
    ports:
      - "4444:4444"
      - "5900:5900"
    network_mode: "host"