title: "Marketplace"

description: >
  A marketplace web application developed in PHP and
  TypeScript (Laravel, Vue.js), similar in functionality
  to Letgo or Facebook's marketplace.

remote_theme: kogli/millidocs